version: '3'

services:
  db:
    image: postgres
    container_name: "bibliotecame_db"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bibliotecame
